---                                                                                                                  

  - name: Confirgure Elk With Docker                                       
    hosts: Elk            
    become: true                                                                                               
    tasks:                                                                                                    
          
   - name: Install docker.io On Elk      
     apt:         
       update_cache: yes                    
       name: docker.io                    
       state: present                                                                                     
   
   - name: Install Pip3 On Elk                                          
     apt:                            
       name: python3-pip                                                                                   
       state: present                                                                  
 
   - name: Install Python Docker Module                                                               
     pip:                                                                                      
       name: docker                                                                             
       state: present                                                 
                                           
   - name: Increase virtual memory                                                             
     command: sysctl -w vm.max_map_count=262144                                                         
   # Use sysctl model         
                                                                 
   - name: Use more memory                                                                   
     sysctl:                                                                                                    
       name: vm.max_map_count                                                                          
       value: 262144                                                                 
       state: present            
       reload: yes                                                         
 
  # Use docker_container module                                                                              
   - name: download and launch a docker elk container                           
     docker_container:                                                   
       name: elk                                                                              
       image: sebp/elk:761                                                               
       state: started                                                                  
       restart_policy: always                                                                   
  # Please list the ports that ELK runs on                                                                   
       published_ports:                                                          
         -  5601:5601                                                    
         -  9200:9200                                                  
         -  5044:5044                                                     
   # Use systemd module                                                    
   - name: Enable service docker on boot                                                         
      systemd:                                                                                              
       name: docker                                                                                      
       enabled: yes
